server {
    listen 80;
    server_name localhost;

    # Gwarantuje ze pliki statyczne sa serwowane poprawnie
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Obsługa tradycyjnego routingu aplikacji SPA (Flutter Web)
        try_files $uri $uri/ /index.html;
    }

    # Reverse proxy dla API
    # Zapytania pod adresem http://.../api/ zostana wyslane do http://webapp:6767/api/
    location /api/ {
        proxy_pass http://webapp:6767/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
